### ISSUE TITLE
Multi-region deployment

### ISSUE THREAD

**Issue by gugaiz** [scalefactory/tfctl#18]
Hi,

Just wondering how you normally deal with multi-region deployments. For example, ACM certificates for CloudFront are only valid on us-east-1 region while I am deploying the infrastructure on us-east-2. How you normally deal with that on `tfctl`? Is it possible to deploy resources on different regions using `tfctl`?

**Comment by word** [comment]
Hey,

You can handle this in Terraform by defining providers for the additional regions in your profile/modules.  See:
https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations

**Comment by word** [comment]
Here's an example of what this could look like:

```
data aws_caller_identity current {}

locals {
  config                       = jsondecode(var.config)
  current_account_id  = data.aws_caller_identity.current.account_id
  current_account       = [ for account in local.config["accounts"]: account if account["id"] == local.current_account_id ][0]
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.current_account_id}:role/${local.current_account["tf_execution_role"]}"
  }
}
```

**Comment by gugaiz** [comment]
Thanks very much for your answer!
