### ISSUE TITLE
I don't find a way to get `terraform output`

### ISSUE THREAD

**Issue by gugaiz** [scalefactory/tfctl#25]
Hi I have tried few things but I don't seems to find a way to get terrafom outputs. Is there something special about it? Can it be done?
Thanks

**Comment by word** [comment]
Hi, 

For the outputs to be visible they need to be defined at the root level of your Terraform, which in this case means the code generated by tfctl.  Unfortunately at the moment tfctl doesn't support this, but it's possible to add this functionality to the generator, similar to how we generate profiles:

https://github.com/scalefactory/tfctl/blob/master/lib/tfctl/generator.rb#L70

**Comment by gugaiz** [comment]
Thanks for your answer... I tried by I failed. In order to test, I went into the `.tfctl/default/<account>/` directory and took my main profile (`profile_general-resources.tf.json`) and added this 

```
"output": {
  "test": {
    "value": "${module.general-resources.iam_user_key}"
  }
}
```

I also added the code below on the resource file inside `profiles/general-resources/iam.tf` 
```
resource "aws_iam_user" "user" {
  name = "test_user"
}

resource "aws_iam_access_key" "user_access_key" {
  user = aws_iam_user.user.name
}

output "iam_user_key" {
  value = aws_iam_access_key.user_access_key.encrypted_secret
}
```

but it is not working (after doing `terraform apply` and `terraform refresh`). Any ideas?

**Comment by word** [comment]
What you have looks correct.  I just tried something similar here and it worked.  Here's what my profile json looks like:

```
{
  "module": {
    "example-profile": {
      "source": "../../../profiles/example-profile",
      "config": "${var.config}",
      "providers": {
        "aws": "aws"
      }
    }
  },
  "output": {
    "test": {
        "value": "${module.example-profile.bucket_arn}"
        }
    }
}
```

Here is the profile itself: 

```
module "bucket" {
  source = "../../modules/s3-bucket"
  name   = "${local.account_id}-${local.account["data"]["example_bucket_name"]}"
}

output "bucket_arn" {
  value = module.bucket.arn
}
```

The bucket module is configured to output the arn too.

Here's what my `terraform apply` looks like:
```
wopr% terraform apply
module.example-profile.data.aws_caller_identity.current: Refreshing state...
module.example-profile.module.bucket.aws_s3_bucket.bucket: Refreshing state... [id=XXXXXXXXXXXX-tfctl-account-override-example]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

test = arn:aws:s3:::XXXXXXXXXXX-tfctl-account-override-example
```

You can also drop the output declaration into a separate json file rather than attaching to existing profile.  This way tfctl won't overwrite it.

**Comment by word** [comment]
Hi, I'm going to close this issue since there has been no further activity.
