### ISSUE TITLE
Terraform 0.14 and AWS provider version configuration

### ISSUE THREAD

**Issue by grothja** [scalefactory/tfctl#28]
Starting in Terraform 0.14, we started to see the following warning from `tfctl`'s Terraform output for all commands:

     Warning: Version constraints inside provider configuration blocks are deprecated

I [took a stab](https://github.com/grothja/tfctl/commit/6d5ef98049a50636d4028abd1712f925d207806e) at supporting this quickly for our org, by adding the AWS provider version specified to the `terraform` block and removing it from the `provider` block when the version of Terraform specified is 0.14+, and it seems to work well for both 0.13 and 0.14.  My implementation works OK for our org because we don't do anything too fancy with the `tf_required_version` string, but there are definitely ways to for that to go wrong, in addition to the version comparison not being robust.

I was wondering if you guys had any thoughts on supporting this, or if you had plans.

**Comment by word** [comment]
Thanks for raising the issue and the example code.  It would be good to support the new syntax and I will be looking into it shortly.  We could potentially bump the minimum version of Terraform for `tfctl` to 0.13 if that makes things simpler but I will need to look into it in more detail first.

**Comment by grothja** [comment]
Thanks @word, tried out your changes in the latest release and it looks good.

**Comment by word** [comment]
Great, thanks for giving it a spin :-)
