### ISSUE TITLE
Enable alias support in yaml config file

### ISSUE THREAD

**Issue by patrickli** [scalefactory/tfctl#31]
Can we please enable alias support in the config file? This can be done by specifying `aliases: true` (https://ruby-doc.org/stdlib-2.6.1/libdoc/psych/rdoc/Psych.html#safe_load-method) at

https://github.com/scalefactory/tfctl/blob/master/bin/tfctl#L149

This way we can have more flexible and DRY configuration files. In fact, the output produced by `tfctl --show-config` uses anchors and aliases.

**Comment by word** [comment]
This is a good idea, thanks.   I just raised a PR with your suggestion and will get it released as soon as it's reviewed.

**Comment by word** [comment]
Released in 1.4.0
